### PR TITLE
Fix build with Qt branch 5.9

### PR DESCRIPTION
**Pull request by aleixpol**
keepassx/tests/modeltest.cpp:451: undefined reference to `bool QTest::qCompare<int, unsigned int>(int const&, unsigned int const&, char const*, char const*, char const*, int)'

### CODE REVIEW

**Comment by debfx** [comment]
Fixed in 181ab27eb9f0bd2b6478f0c22684b742d44c4e2f
